import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';
import font from '../../utils/CustomFont';
import { wp, hp } from '../../utils/size';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white.default,
    paddingHorizontal: '5%',

  },
  profileNameCon: {
    width: '60%',
    flexDirection: 'row',
    alignItems: 'center',
    // borderWidth: 1,
  },
  profile: {
    marginTop: '5%',
    // borderWidth: 1,
  },
  profileNameText: {
    // borderWidth: 1,
    width: '80%',
    color: colors.black.default,
    fontSize: 20,
    fontFamily: font.AkrobatSB,
  },
  connectIcCon: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 42,
    borderWidth: 0.3,
    borderColor: colors.grey.default,
    backgroundColor: colors.white.default,
    borderRadius: 5,
  },
  connectIc: {
    width: 27,
    height: 27,
  },
  imagesSectionCon: {
    marginTop: '4%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  horizontalImageCon: {
    borderStyle: 'dashed',
    backgroundColor: colors.grey.lightGrey,
    borderColor: colors.grey.default,
    justifyContent: 'center',
    alignItems: 'center',
    width: '60%',
    height: 135,
    borderWidth: 1.4,
    borderRadius: 10,
  },
  horizontalImage: {
    width: '100%',
    height: '100%',
  },
  horizontalImageText: {
    fontSize: 17,
    color: colors.black.default,
    fontFamily: font.AkrobatSB,
  },
  verticalImageCon: {
    position: 'absolute',
    right: 0,
    borderStyle: 'dashed',
    backgroundColor: colors.grey.lightGrey,
    borderColor: colors.grey.default,
    justifyContent: 'center',
    alignItems: 'center',
    width: '37%',
    height: '100%',
    borderWidth: 1.4,
    borderRadius: 10,
  },
  verticalImageText: {
    textAlign: 'center',
    fontSize: 17,
    color: colors.black.default,
    fontFamily: font.AkrobatSB,
  },
  tasksCon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: '3%',
    // borderWidth: 1,
  },
  tasksText: {
    fontSize: 17,
    color: colors.black.default,
    fontFamily: font.AkrobatSB,
  },
  dateDayText: {
    fontSize: 16,
    color: colors.black.default,
    fontFamily: font.AkrobatSB,
  },
  forumsText: {
    paddingVertical: '3%',
    // borderWidth: 1,
    fontSize: 17,
    color: colors.black.default,
    fontFamily: font.AkrobatSB,
  },
  forumCon: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  blogText: {
    marginTop: '4%',
    fontSize: 22,
    textAlign: 'center',
    // color: colors.orange.lightOrange,
  },
  authorText: {
    paddingVertical: '2%',
    fontSize: 14,
    textAlign: 'center',
    // color: colors.orange.lightOrange,
  },
  forumBottomText: {
    padding: '2%',
    fontSize: 14,
    // color: colors.orange.lightOrange,
  },
  menuIcCon: {
    // marginTop: '3%',
    // borderWidth: 1,
    // alignSelf: 'flex-start',
    position: 'absolute',
    bottom: hp(5),
    left: wp(3),
    width: wp(15),
    height: wp(15),
  },
  menuIc: {
    width: wp(15),
    height: wp(15),
    resizeMode: 'contain',
  },
  connectPopup: {
    borderRadius: 4,
    // padding: '0.5%',
    paddingHorizontal: '1.3%',
    paddingVertical: '0.5%',
    backgroundColor: colors.grey.darkGrey,
    left: '45%',
    top: -22,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    borderWidth: 1,
  },
  connectText: {
    fontSize: 9,
    fontFamily: font.QuicksandM,
    color: colors.white.default,
  },
  triangle: {
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    position: 'absolute',
    bottom: -6,
    right: 30,
    alignSelf: 'flex-end',
  },
  arrowDown: {
    borderTopWidth: 8,
    borderRightWidth: 5,
    borderLeftWidth: 5,
    borderTopColor: colors.grey.darkGrey,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRadius: 5,
  },
  menuBox: {
    position: 'absolute',
    bottom: hp(13),
    // borderWidth: 1,
    left: wp(5),
  },
  menuBtn: {
    borderWidth: 1,
    height: hp(5),
    width: wp(45),
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderRadius: 7,
    paddingHorizontal: wp(5),
    marginBottom: hp(1),
  },
  menuBtnText: {
    fontFamily: font.AkrobatSB,
    fontSize: 20,
    color: '#000',
  },
  redDot: {
    height: wp(3),
    width: wp(3),
    borderRadius: wp(5),
    backgroundColor: 'red',
    position: 'absolute',
    right: wp(5),
  },
  Modalview: {
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  ModalItem: {
    height: 100,
    backgroundColor: 'white',
    width: '80%',
    borderRadius: 15,
    marginBottom: 30,
    justifyContent: 'center',
  },
  close: {
    alignSelf: 'flex-end',
    right: 10,
    top: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    height: 20,
    width: 20,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  button: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    // alignSelf:"center"
  },
  Icon: {
    height: 50,
    width: 50,
  },
  rowContainer: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    marginBottom: hp(3.5),
  },
  rowContainerChoice: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(3.5),
  },
  modalBase: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalInnerContainer: {
    position: 'relative',
    width: wp(90),
    padding: wp(7),
    backgroundColor: '#fff',
    borderRadius: 20, // Rounded border
    borderColor: 'black', // If you want the border color to be red
    borderWidth: 1, // Border width
    elevation: 5,
    shadow: {
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
        },
        android: {
          elevation: 5,
        },
      }),
    },
  },
  iconStyle: {
    marginTop: hp(0.5),
    width: wp(8),
    height: wp(7),
    resizeMode: 'contain',
    // borderWidth: 1,
  },
  vSeparator: {
    borderWidth: 1,
    marginHorizontal: wp(3),
  },
  choiceTitle: {
    fontFamily: font.AkrobatSB,
    fontSize: 30,
    // width: wp(5),
    color: '#000000',
  },
  modalText: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    maxWidth: wp(65),
    top : -5,
    color: '#000000',
    // borderWidth: 1,
    // flex: 1,
  },
  textInput: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    flex: 1,
    borderBottomWidth: 1,
    // borderWidth: 1,
  },
  sendBtn: {
    borderWidth: 1,
    paddingVertical: 7,
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 30,
    backgroundColor: '#000',
    marginTop: hp(2),
  },
  btnText: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    color: '#fff',
  },
  hiddenBtn: {
    position: 'absolute',
    ...StyleSheet.absoluteFill,
  },
});

export default styles;
