import {StyleSheet} from 'react-native';
import font from '../../utils/CustomFont';

const styles = StyleSheet.create({
  text: {
    fontFamily: font.AkrobatSB,
    fontSize: 20,
    color: 'black',
    marginBottom: 10,
  },
  text1: {
    fontFamily: font.AkrobatB,
    fontSize: 22,
    color: 'black',
    marginRight: 31,
    alignSelf: 'flex-end',
  },
  text2: {
    fontFamily: font.AkrobatR,
    fontSize: 18,
    color: 'black',
  },
  contactName: {
    fontFamily: font.QuicksandM,
    fontSize: 12,
    color: 'black',
  },
  contactNumber: {
    fontFamily: font.QuicksandR,
    fontSize: 12,
    color: 'black',
  },
  remove: {
    fontFamily: font.QuicksandR,
    fontSize: 10,
    color: 'black',
  },
  button: {
    width: '90%',
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 10,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
    borderRadius: 9,
  },

  textbutton: {
    fontFamily: font.AkrobatR,
    color: 'white',
    fontSize: 20,
  },
  bottomTxt: {
    fontFamily: font.AkrobatR,
    color: 'white',
    fontSize: 23,
  },
  topTxt: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    color: 'black',
    marginLeft: 10,
  },
  topBody: {
    borderWidth: 1,
    borderColor: '#707070',
    backgroundColor: '#ffffff',
    marginTop: 10,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  inviteBody: {
    width: '95%',
    marginTop: -40,
    borderWidth: 3,
    borderColor: '#707070',
    borderRadius: 24,
    backgroundColor: '#fff',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bottomBody: {
    borderTopWidth: 1,
    borderTopColor: '#5D6468',
    backgroundColor: '#fff',
    height: 96,
    justifyContent: 'center',
    display: 'flex',
  },

  next: {
    backgroundColor: 'black',
    borderRadius: 30,
    borderColor: '#707070',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 43,
    width: '90%',
    marginLeft: 'auto',
    marginRight: 'auto',
    // alignSelf: 'flex-end',
  },
  close: {
    alignSelf: 'flex-end',
    right: 5,
    top: 5,
    backgroundColor: 'rgba(0,0,0,0.3)',
    height: 40,
    width: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
});
export default styles;
