import {StyleSheet} from 'react-native';
import font from '../../utils/CustomFont';
const styles = StyleSheet.create({
  text: {
    fontFamily: font.AkrobatR,
    fontSize: 30,
    color: 'black',
  },
  text1: {
    fontFamily: font.AkrobatB,
    fontSize: 22,
    color: 'black',
    marginRight: 31,
    alignSelf: 'flex-end',
  },
  topTxt: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    color: 'black',
    marginLeft: 10,
  },
  Add: {
    width: 143,
    height: 91,
    backgroundColor: 'white',
    borderColor: '#707070',
    marginTop: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plus: {
    fontFamily: font.AkrobatR,
    fontSize: 30,
    color: '#707070',
  },
  skipText: {
    color: '#134634',
    marginLeft: '5%',
    position: 'absolute',
    bottom: '2%',
    fontSize: 18,
    fontFamily: font.AkrobatSB,
  },
  body: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#707070',
    backgroundColor: '#ffffff',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    height: '70%',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },

  Icon: {
    height: 50,
    width: 50,
  },
  nameInput: {
    borderColor: '#707070',
    borderWidth: 1,
    backgroundColor: '#fff',
    width: '80%',
    justifyContent: 'center',
    display: 'flex',
    marginTop: -25,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 23,
    height: 40,
  },
  inputTxt: {
    fontFamily: font.AkrobatSB,
    fontSize: 18,
    lineHeight: 24,
    color: '#000',
    opacity: 0.5,
  },
  buttontext: {
    color: 'white',
    fontSize: 23,
    fontFamily: font.AkrobatR,
    paddingTop: 6,
  },
  button: {
    width: '95%',
    height: 43,
    borderRadius: 40,
    backgroundColor: '#000',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  button2: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    // alignSelf:"center"
  },
  close: {
    alignSelf: 'flex-end',
    right: 10,
    top: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    height: 20,
    width: 20,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  ModalItem: {
    height: 100,
    backgroundColor: 'white',
    width: '80%',
    borderRadius: 15,
    marginBottom: 30,
    justifyContent: 'center',
  },

  Modalview: {
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },

  tapImgTxt: {
    fontFamily: font.QuicksandM,
    fontSize: 14,
    color: '#fff',
  },
});
export default styles;
